# Generated by Django 4.2 on 2025-04-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['email'], name='participant_email_3b27de_idx'),
        ),
    ]
